# Generated by Django 4.0.3 on 2022-03-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Usuário com acesso ao painel gerald e administração', verbose_name='pertence a administração'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('USER', 'Usuário'), ('STORE', 'Lojá'), ('MANAGER_STORE', 'Gerente de lojá'), ('ADMIN', 'Administrador')], default='USER', max_length=25),
        ),
    ]
